# Generated by Django 5.0.3 on 2024-03-26 21:13

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0002_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.TextField(blank=True, default='Professor Cahan', null=True, validators=[subject_app.validators.validate_professor_name]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.TextField(blank=True, default='Python', null=True, unique=True, validators=[subject_app.validators.validate_subject_format]),
        ),
    ]
