# Generated by Django 5.0.3 on 2024-03-23 17:30

import student_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_alter_student_locker_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='locker_combination',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[student_app.validators.validate_combination_format]),
        ),
    ]
